query($name: String) {
  exercises(where: {
    name: $name
  }) {
    id
    name
    subcategory {
      name
      id
    }
    positioning
    technique
    images {
      id
      url
    }
  }
}