query($username: String) {
  users(where:{
    username: $username
  }) {
    id
    email
    username
    fullname
    image {
      url
    }
    workouts(sort: "createdAt:desc", where: { sticky_ne: "true" } ) {
      id
      scheduled
      ready
    }
    homeworks: workouts(where: { sticky: "true" } ) {
      id
      scheduled
      ready
    }
    skill {
      id
      units {
        ...on ComponentBlockUnit {
          id
          sets
          reps
          distance
          time
          remarks
          exercise {
            name
            id
            _id
            subcategory {
              _id
              id
              name
              category {
                _id
                id
                name
              }
            }
          }
        }
      }
    }
  }
}