query($id: ID!) {
  workout(id: $id) {
    id
    sections {
      id
      name
      rest
      complexes {
        name 
        id
        units {
          id
          sets
          reps
          time
          distance 
          remarks
          exercise {
            id
            name
            images {
              url
            }
          }
        }
      }
    }
  }
}