query($ids: [ID]!) {
  workouts(where: { id_in: $ids }) {
    user {
      id
      fullname
    }
    id
    sections {
      id
      name
      complexes {
        name 
        id
        units {
          id
          sets
          reps
          time
          distance 
          rest
          remarks
          exercise {
            id
            name
            images {
              id
              url
            }
          }
        }
      }
    }
  }
}