query($username: String, $today: DateTime) {
  users(where:{
    username: $username
  }) {
    id
    username
    fullname
    image {
      url
    }
    workouts(limit: 1, sort: "scheduled:asc", where: { scheduled_gt: $today, sticky_ne: "true" } ) {
      id
      scheduled
      ready
    }
  }
}