query($username: String) {
  users(where:{
    username: $username
  }) {
    id
    username
    fullname
    image {
      id
      url
    }
    workouts(sort: "createdAt:desc", where: { sticky_ne: "true" } ) {
      id
      scheduled
      ready
    }
    homeworks: workouts(where: { sticky: "true" }) {
      id
      scheduled 
      ready
      sticky
    }
  }
}