query($username: String) {
  users(where: { username: $username }) {
    id
    username
    email
    image {
      url
    }
    homeworks: workouts(where: { sticky: "true" }) {
      id
      scheduled 
      ready
      sticky
    }
    workouts( sort: "scheduled:desc", where: { sticky_ne: "true" } ) {
      id
      scheduled
      ready
      sticky
    }
  }
}