query($ids: [ID]!) {
  workouts(where: { id_in: $ids }) {
    id
    scheduled
    sticky
    feedback
    user {
      id
      fullname
      username
    } 
    sections {
      id
      name
      complexes {
        id
        name 
        units {
          id
          sets
          reps
          time
          distance 
          rest
          remarks
          max
          exercise {
            id
            name
            subcategory {
              id
              name
              category {
                id
                name
              }
            }
          }
        }
      }
    }
  }
}