query($ids: [ID]!) {
  workouts(where: { id_in: $ids }) {
    id
    createdAt
    scheduled
    sticky
    name
    feedback
    user {
      id
      fullname
      username
    } 
    sections {
      id
      name
      complexes {
        id
        name 
        units {
          id
          sets
          reps
          time
          distance 
          rest
          remarks
          exercise {
            id
            name
            image {
              id
              url
            }
          }
        }
      }
    }
  }
}