query($id: ID!) {
  workout(id: $id) {
    id
    scheduled
    afterBlockRest
    singleExerciseRest
    pairedExerciseRest
    warmupRest
    user {
      id
      fullname
      image {
        url
      }
    } 
    warmup {
      ...on ComponentBlockCombo {
        name
        units {
          id
          exercise {
            name
            _id
          }
          sets
          reps
          time
          distance
          remarks
        }
      }
    }
    skillwork {
      ...on ComponentBlockCombo {
        name
        units {
          id
          exercise {
            name
            _id
          }
          sets
          reps
          time
          distance
          remarks
        }
      }
    }
    strength {
      ...on ComponentBlockCombo {
        name
        units {
          id
          exercise {
            name
            id
          }
          sets
          reps
          time
          distance
          remarks
        }
      }
    }
    cardio {
      ...on ComponentBlockCombo {
        name
        units {
          id
          exercise {
            name
            id
          }
          sets
          reps
          time
          distance
          remarks
        }
      }
    }
    mobility {
      ...on ComponentBlockCombo {
        name
        units {
          id
          exercise {
            name
            id
          }
          sets
          reps
          time
          distance
          remarks
        }
      }
    }
  }
}