query($id: ID!) {
  user(id: $id) {
    id
    username
    fullname
    image {
      id
      url
    }
    workouts(sort: "scheduled:desc") {
      id
      scheduled
      ready
      sticky
      createdAt
    }
  }
}