query($id: ID!) {
  users(where:{
    id: $id
  }) {
    workouts(sort: "scheduled:desc", where: { sticky_ne: "true" }) {
      id
      scheduled
      ready
      sticky
    }
    homeworks: workouts(where: { sticky: "true" }) {
      id
      scheduled 
      ready
      sticky
    }
  }
}