query($id: ID!, $copiedWorkoutId: ID!) {
  workout(id: $id) {
    id
    scheduled
    sticky
    name
    feedback
    sections {
      id
      name
      complexes {
        name 
        id
        units {
          id
          sets
          reps 
          time
          distance
          rest
          remarks
          exercise {
            id
            name
            image {
              id
              url
            }
          }
        }
      }
    }
    user {
      id
      fullname
      workouts(sort: "scheduled:desc", where: { id_ne: $id, sticky_ne: "true", ready: "true" }) {
        id
        scheduled
        feedback
        sections {
          id
          name
          complexes {
            name 
            id
            units {
              id
              sets
              reps
              time
              distance
              rest
              remarks
              exercise {
                id
                name
                image {
                  id
                  url
                }
              }
            }
          }
        }
      }
    } 
  }
  copiedWorkout: workout(id: $copiedWorkoutId) {
    id
    scheduled
    feedback
    sticky
    user {
      id
      username
    }
    sections {
      id
      name
      complexes {
        name 
        id
        units {
          id
          sets
          reps 
          time
          distance
          rest
          remarks
          exercise {
            id
            name
            image {
              id
              url
            }
          }
        }
      }
    }
  }
}