query($id: ID!) {
  workout(id: $id) {
    id
    scheduled
    sticky
    sections {
      id
      name
      complexes {
        name 
        id
        units {
          id
          sets
          reps 
          time
          distance
          rest
          remarks
          max
          exercise {
            id
            name
          }
        }
      }
    }
    user {
      id
      fullname
      workouts(sort: "scheduled:desc", where: { id_ne: $id, sticky_ne: "true" }) {
        id
        scheduled
        sections {
          id
          name
          complexes {
            name 
            id
            units {
              id
              sets
              reps
              time
              distance
              rest
              remarks
              max
              exercise {
                id
                name
              }
            }
          }
        }
      }
    } 
  }
}