query($id: ID!) {
  workout(id: $id) {
    id
    scheduled
    sticky
    sections {
      id
      name
      rest
      complexes {
        name 
        id
        units {
          id
          sets
          reps 
          remarks
          exercise {
            id
            name
            subcategory {
              id
              name
              category {
                id
                name
              }
            }
          }
        }
      }
    }
    user {
      id
      fullname
      skill {
        id
        skillsets {
          id
          name
          units {
            ...on ComponentBlocksUnit {
              id
              sets
              reps
              distance
              time
              remarks
              exercise {
                name
                id
              }
            }
          }
        }
      }
      workouts(sort: "scheduled:desc", where: { id_ne: $id, sticky_ne: "true" }) {
        id
        scheduled
        sections {
          id
          name
          rest
          complexes {
            name 
            id
            units {
              id
              sets
              reps 
              remarks
              exercise {
                id
                name
              }
            }
          }
        }
      }
    } 
  }
}