query getSingleFamily($id: ID!) {
  family(id: $id) {
    id
    name
    alias
    description
    exercises {
      id
      name
      alias
      image {
        id
        url
      }
    }
  }
}