query($id: ID, $email: String) {
  user(id: $id, email: $email) {
    id
    username
    fullname
    admin
    image {
      id
      url
    }
    workouts {
      id
      scheduled
      ready
      sticky
      name
      createdAt
    }
  }
}