query($username: String, $copiedWorkoutId: ID!) {
  users( where: { username: $username } ) {
    id
    username
    workouts(limit: 3, sort: "scheduled:desc", where: { sticky_ne: "true" }) {
      id
      scheduled
      sections {
        id
        name
        complexes {
          name 
          id
          units {
            id
            sets
            reps
            time
            distance
            rest
            max 
            remarks
            exercise {
              id
              name
            }
          }
        }
      }
    }
  }
  copiedWorkout: workout(id: $copiedWorkoutId) {
    id
    scheduled
    sticky
    user {
      id
      username
    }
    sections {
      id
      name
      rest
      complexes {
        name 
        id
        units {
          id
          sets
          reps 
          time
          distance
          rest
          remarks
          max
          exercise {
            id
            name
          }
        }
      }
    }
  }
}