query($username: String) {
  users( where: { username: $username } ) {
    id
    username
    skill {
      id
      skillsets {
        id
        name
        units {
          ...on ComponentBlocksUnit {
            id
            sets
            reps
            distance
            time
            remarks
            exercise {
              name
              id
              subcategory {
                id
                name
                category {
                  id
                  name
                }
              }
            }
          }
        }
      }
    }
    workouts(limit: 3, sort: "scheduled:desc", where: { sticky_ne: "true" }) {
      id
      scheduled
      sections {
        id
        name
        rest
        complexes {
          name 
          id
          units {
            id
            sets
            reps
            time
            distance
            max 
            remarks
            exercise {
              id
              name
            }
          }
        }
      }
    }
  }
}