query($username: String) {
  users( where: { username: $username } ) {
    id
    username
    skill {
      id
      units {
        ...on ComponentBlockUnit {
          id
          sets
          reps
          distance
          time
          remarks
          exercise {
            name
            id
            _id
            subcategory {
              _id
              id
              name
              category {
                _id
                id
                name
              }
            }
          }
        }
      }
    }
    homeworks: workouts(where: { sticky: "true" } ) {
      id
    }
    workouts(limit: 3, sort: "scheduled:desc") {
      id
      scheduled
      warmup {
        ...on ComponentBlockCombo {
          id
          name
          units {
            id
            exercise { 
              name
              _id
            }
            sets
            reps
            time
            distance
            remarks
          }
        }
      }
      skillwork {
        ...on ComponentBlockCombo {
          id
          name
          units {
            id
            exercise {
              name
              _id
            }
            sets
            reps
            time
            distance
            remarks
          }
        }
      }
      strength {
        ...on ComponentBlockCombo {
          id
          name
          units {
            id
            exercise {
              name
              id
            }
            sets
            reps
            time
            distance
            remarks
          }
        }
      }
      cardio {
        ...on ComponentBlockCombo {
          id
          name
          units {
            id
            exercise {
              name
              id
            }
            sets
            reps
            time
            distance
            remarks
          }
        }
      }
      mobility {
        ...on ComponentBlockCombo {
          id
          name
          units {
            id
            exercise {
              name
              id
            }
            sets
            reps
            time
            distance
            remarks
          }
        }
      }
    }
  }
}